repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.6 
    hooks:
      # Ensures uv.lock is up-to-date with pyproject.toml
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format